nelmio_cors:
    defaults:
        allow_origin: ['*']  # Mets l'URL de ton frontend si besoin
        allow_methods: ['GET', 'POST', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
    paths:
        '^/api/':
            allow_origin: ['*']  # Mets l'URL de ton frontend (ex: http://localhost:3000)
            allow_methods: ['GET', 'POST', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600

