services:
  php:
    build:
      context: docker
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./docker/php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    working_dir: /app
    command: php-fpm
    environment:
      - PHP_IDE_CONFIG="serverName=php"

  nginx:
    image: nginx:latest
    volumes:
      - './docker/nginx.conf:/etc/nginx/conf.d/default.conf'
      - ./:/app
    depends_on:
      - php
    ports:
      - '8080:80'